///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace sample3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the sample3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a057ad94-fb66-4602-89da-766c447faf3e")]
    public partial class sample3Repository : RepoGenBaseFolder
    {
        static sample3Repository instance = new sample3Repository();

        /// <summary>
        /// Gets the singleton class instance representing the sample3Repository element repository.
        /// </summary>
        [RepositoryFolder("a057ad94-fb66-4602-89da-766c447faf3e")]
        public static sample3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public sample3Repository() 
            : base("sample3Repository", "/", null, 0, false, "a057ad94-fb66-4602-89da-766c447faf3e", ".\\RepositoryImages\\sample3Repositorya057ad94.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a057ad94-fb66-4602-89da-766c447faf3e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class sample3RepositoryFolders
    {
    }
#pragma warning restore 0436
}
